package com.androidapp.vshopandroidapp.core.designsystem

import androidx.compose.ui.graphics.Color

// Brand: teal (trust, banking) + warm amber accent (prices, highlights)
val TealPrimary = Color(0xFF0B6E7A)
val TealPrimaryDark = Color(0xFF82D3DD)
val TealContainerLight = Color(0xFFC9ECEF)
val TealContainerDark = Color(0xFF004F57)
val OnTealContainerLight = Color(0xFF002024)
val OnTealContainerDark = Color(0xFFA6EFF9)

val Slate = Color(0xFF4A6366)
val SlateDark = Color(0xFFB1CCCF)
val SlateContainerLight = Color(0xFFCCE8EB)
val OnSlateContainerLight = Color(0xFF051F22)
val SlateContainerDark = Color(0xFF324B4E)
val OnSlateContainerDark = Color(0xFFCCE8EB)

val Amber = Color(0xFF8A5100)
val AmberDark = Color(0xFFFFB95F)
val AmberContainerLight = Color(0xFFFFDDB7)
val OnAmberContainerLight = Color(0xFF2C1600)
val AmberContainerDark = Color(0xFF693C00)
val OnAmberContainerDark = Color(0xFFFFDDB7)

// Status
val ErrorRed = Color(0xFFBA1A1A)
val ErrorRedDark = Color(0xFFFFB4AB)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val SuccessGreen = Color(0xFF1E8A4C)
val SuccessGreenDark = Color(0xFF6DD69A)
val SuccessContainerLight = Color(0xFFD5F2DF)
val OnSuccessContainerLight = Color(0xFF0B3D20)
val SuccessContainerDark = Color(0xFF12472A)
val OnSuccessContainerDark = Color(0xFFBDEFCF)
val WarningContainerLight = Color(0xFFFFE9C7)
val OnWarningContainerLight = Color(0xFF5A3500)
val WarningContainerDark = Color(0xFF4F3000)
val OnWarningContainerDark = Color(0xFFFFDDB0)
val InfoContainerLight = Color(0xFFDDE7FF)
val OnInfoContainerLight = Color(0xFF14305E)
val InfoContainerDark = Color(0xFF223A66)
val OnInfoContainerDark = Color(0xFFD7E3FF)

// Neutrals
val SurfaceLight = Color(0xFFF6F8F9)
val SurfaceDark = Color(0xFF0E1415)
val OnSurfaceLight = Color(0xFF171D1E)
val OnSurfaceDark = Color(0xFFDEE3E4)
val SurfaceVariantLight = Color(0xFFDAE4E5)
val SurfaceVariantDark = Color(0xFF3F484A)
val OnSurfaceVariantLight = Color(0xFF3F484A)
val OnSurfaceVariantDark = Color(0xFFBEC8C9)
val OutlineLight = Color(0xFF6F797A)
val OutlineDark = Color(0xFF899294)
val OutlineVariantLight = Color(0xFFD5DEDF)
val OutlineVariantDark = Color(0xFF2E3638)

// Tonal surfaces layered above the background (cards, skeletons, sheets).
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF0F4F5)
val SurfaceContainerLight = Color(0xFFEAEFF0)
val SurfaceContainerHighLight = Color(0xFFE4E9EA)
val SurfaceContainerHighestLight = Color(0xFFDEE3E4)
val SurfaceContainerLowestDark = Color(0xFF090F10)
val SurfaceContainerLowDark = Color(0xFF171D1E)
val SurfaceContainerDark = Color(0xFF1B2122)
val SurfaceContainerHighDark = Color(0xFF252B2C)
val SurfaceContainerHighestDark = Color(0xFF303637)